// Code generated by entc, DO NOT EDIT.

package handler

import (
	"encoding/json"
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/chi"
	"github.com/go-playground/validator/v10"
	"github.com/liip/sheriff"
	"github.com/masseelch/render"
	"github.com/sirupsen/logrus"

	"skeleton/ent"
	"skeleton/ent/account"
	"skeleton/ent/tag"
	"skeleton/ent/transaction"
	"skeleton/ent/user"
)

// The AccountHandler.
type AccountHandler struct {
	*chi.Mux

	client    *ent.Client
	validator *validator.Validate
	logger    *logrus.Logger
}

// Create a new AccountHandler
func NewAccountHandler(c *ent.Client, v *validator.Validate, log *logrus.Logger) *AccountHandler {
	return &AccountHandler{
		Mux:       chi.NewRouter(),
		client:    c,
		validator: v,
		logger:    log,
	}
}

// Enable all endpoints.
func (h *AccountHandler) EnableAllEndpoints() *AccountHandler {
	h.EnableCreateEndpoint()
	h.EnableReadEndpoint()
	h.EnableUpdateEndpoint()
	h.EnableListEndpoint()
	h.EnableUsersEndpoint()
	h.EnableTransactionsEndpoint()
	return h
}

// Enable the create operation.
func (h *AccountHandler) EnableCreateEndpoint() *AccountHandler {
	h.Post("/", h.Create)
	return h
}

// struct to bind the post body to.
type accountCreateRequest struct {
	Title        string `json:"title,omitempty" `
	Users        []int  `json:"users,omitempty" `
	Transactions []int  `json:"transactions,omitempty" `
}

// This function creates a new Account model and stores it in the database.
func (h AccountHandler) Create(w http.ResponseWriter, r *http.Request) {
	// Get the post data.
	d := accountCreateRequest{} // todo - allow form-url-encdoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.Account.Create().
		SetTitle(d.Title).
		AddUserIDs(d.Users...).
		AddTransactionIDs(d.Transactions...)

	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving Account")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"account:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Account.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("account", e.ID).Info("account rendered")
	render.OK(w, r, j)
}

// Enable the read operation.
func (h *AccountHandler) EnableReadEndpoint() *AccountHandler {
	h.Get("/{id:\\d+}", h.Read)
	return h
}

// This function fetches the Account model identified by a give url-parameter from
// database and returns it to the client.
func (h AccountHandler) Read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Account.Query().Where(account.ID(id))

	e, err := qb.Only(r.Context())

	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).WithField("Account.id", id).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).WithField("Account.id", id).Error("duplicate entry for id")
			render.InternalServerError(w, r, nil)
			return
		default:
			h.logger.WithError(err).WithField("Account.id", id).Error("error fetching node from db")
			render.InternalServerError(w, r, nil)
			return
		}
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"account:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Account.id", id).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("account", e.ID).Info("account rendered")
	render.OK(w, r, d)
}

// Enable the update operation.
func (h *AccountHandler) EnableUpdateEndpoint() *AccountHandler {
	h.Get("/{id:\\d+}", h.Update)
	return h
}

// struct to bind the post body to.
type accountUpdateRequest struct {
	Title        string `json:"title,omitempty" `
	Users        []int  `json:"users,omitempty" `
	Transactions []int  `json:"transactions,omitempty" `
}

// This function updates a given Account model and saves the changes in the database.
func (h AccountHandler) Update(w http.ResponseWriter, r *http.Request) {

	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	// Get the post data.
	d := accountUpdateRequest{} // todo - allow form-url-encoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.Account.UpdateOneID(id).
		SetTitle(d.Title).
		AddUserIDs(d.Users...).
		AddTransactionIDs(d.Transactions...)

	// Save in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving Account")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"account:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Account.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("account", e.ID).Info("account rendered")
	render.OK(w, r, j)
}

// Enable the list operation.
func (h *AccountHandler) EnableListEndpoint() *AccountHandler {
	h.Get("/", h.List)
	return h
}

// This function queries for Account models. Can be filtered by query parameters.
func (h AccountHandler) List(w http.ResponseWriter, r *http.Request) {
	q := h.client.Account.Query()

	// Pagination
	var err error
	page := 1
	itemsPerPage := 30

	if d := r.URL.Query().Get("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("itemsPerPage", d).Info("error parsing query parameter 'itemsPerPage'")
			render.BadRequest(w, r, "itemsPerPage must be a positive integer greater zero")
			return
		}
	}

	if d := r.URL.Query().Get("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("page", d).Info("error parsing query parameter 'page'")
			render.BadRequest(w, r, "page must be a positive integer greater zero")
			return
		}
	}

	q = q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage)

	// Use the query parameters to filter the query. todo - nested filter?
	if f := r.URL.Query().Get("title"); f != "" {
		q = q.Where(account.Title(f))
	}

	es, err := q.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"account:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("account rendered")
	render.OK(w, r, d)
}

// Enable the read operation on the users edge.
func (h *AccountHandler) EnableUsersEndpoint() *AccountHandler {
	h.Get("/{id:\\d+}/users", h.Users)
	return h
}

func (h AccountHandler) Users(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Account.Query().Where(account.ID(id)).QueryUsers()

	es, err := qb.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"user:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("user rendered")
	render.OK(w, r, d)

}

// Enable the read operation on the transactions edge.
func (h *AccountHandler) EnableTransactionsEndpoint() *AccountHandler {
	h.Get("/{id:\\d+}/transactions", h.Transactions)
	return h
}

func (h AccountHandler) Transactions(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Account.Query().Where(account.ID(id)).QueryTransactions()

	es, err := qb.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"transaction:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("transaction rendered")
	render.OK(w, r, d)

}

// The TagHandler.
type TagHandler struct {
	*chi.Mux

	client    *ent.Client
	validator *validator.Validate
	logger    *logrus.Logger
}

// Create a new TagHandler
func NewTagHandler(c *ent.Client, v *validator.Validate, log *logrus.Logger) *TagHandler {
	return &TagHandler{
		Mux:       chi.NewRouter(),
		client:    c,
		validator: v,
		logger:    log,
	}
}

// Enable all endpoints.
func (h *TagHandler) EnableAllEndpoints() *TagHandler {
	h.EnableCreateEndpoint()
	h.EnableReadEndpoint()
	h.EnableUpdateEndpoint()
	h.EnableListEndpoint()
	return h
}

// Enable the create operation.
func (h *TagHandler) EnableCreateEndpoint() *TagHandler {
	h.Post("/", h.Create)
	return h
}

// struct to bind the post body to.
type tagCreateRequest struct {
	Title       string `json:"title,omitempty" `
	Description string `json:"description,omitempty" `
}

// This function creates a new Tag model and stores it in the database.
func (h TagHandler) Create(w http.ResponseWriter, r *http.Request) {
	// Get the post data.
	d := tagCreateRequest{} // todo - allow form-url-encdoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.Tag.Create().
		SetTitle(d.Title).
		SetDescription(d.Description)

	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving Tag")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"tag:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Tag.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("tag", e.ID).Info("tag rendered")
	render.OK(w, r, j)
}

// Enable the read operation.
func (h *TagHandler) EnableReadEndpoint() *TagHandler {
	h.Get("/{id:\\d+}", h.Read)
	return h
}

// This function fetches the Tag model identified by a give url-parameter from
// database and returns it to the client.
func (h TagHandler) Read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Tag.Query().Where(tag.ID(id))

	e, err := qb.Only(r.Context())

	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).WithField("Tag.id", id).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).WithField("Tag.id", id).Error("duplicate entry for id")
			render.InternalServerError(w, r, nil)
			return
		default:
			h.logger.WithError(err).WithField("Tag.id", id).Error("error fetching node from db")
			render.InternalServerError(w, r, nil)
			return
		}
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"tag:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Tag.id", id).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("tag", e.ID).Info("tag rendered")
	render.OK(w, r, d)
}

// Enable the update operation.
func (h *TagHandler) EnableUpdateEndpoint() *TagHandler {
	h.Get("/{id:\\d+}", h.Update)
	return h
}

// struct to bind the post body to.
type tagUpdateRequest struct {
	Title       string `json:"title,omitempty" `
	Description string `json:"description,omitempty" `
}

// This function updates a given Tag model and saves the changes in the database.
func (h TagHandler) Update(w http.ResponseWriter, r *http.Request) {

	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	// Get the post data.
	d := tagUpdateRequest{} // todo - allow form-url-encoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.Tag.UpdateOneID(id).
		SetTitle(d.Title).
		SetDescription(d.Description)

	// Save in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving Tag")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"tag:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Tag.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("tag", e.ID).Info("tag rendered")
	render.OK(w, r, j)
}

// Enable the list operation.
func (h *TagHandler) EnableListEndpoint() *TagHandler {
	h.Get("/", h.List)
	return h
}

// This function queries for Tag models. Can be filtered by query parameters.
func (h TagHandler) List(w http.ResponseWriter, r *http.Request) {
	q := h.client.Tag.Query()

	// Pagination
	var err error
	page := 1
	itemsPerPage := 30

	if d := r.URL.Query().Get("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("itemsPerPage", d).Info("error parsing query parameter 'itemsPerPage'")
			render.BadRequest(w, r, "itemsPerPage must be a positive integer greater zero")
			return
		}
	}

	if d := r.URL.Query().Get("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("page", d).Info("error parsing query parameter 'page'")
			render.BadRequest(w, r, "page must be a positive integer greater zero")
			return
		}
	}

	q = q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage)

	// Use the query parameters to filter the query. todo - nested filter?
	if f := r.URL.Query().Get("title"); f != "" {
		q = q.Where(tag.Title(f))
	}

	if f := r.URL.Query().Get("description"); f != "" {
		q = q.Where(tag.Description(f))
	}

	es, err := q.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"tag:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("tag rendered")
	render.OK(w, r, d)
}

// The TransactionHandler.
type TransactionHandler struct {
	*chi.Mux

	client    *ent.Client
	validator *validator.Validate
	logger    *logrus.Logger
}

// Create a new TransactionHandler
func NewTransactionHandler(c *ent.Client, v *validator.Validate, log *logrus.Logger) *TransactionHandler {
	return &TransactionHandler{
		Mux:       chi.NewRouter(),
		client:    c,
		validator: v,
		logger:    log,
	}
}

// Enable all endpoints.
func (h *TransactionHandler) EnableAllEndpoints() *TransactionHandler {
	h.EnableCreateEndpoint()
	h.EnableReadEndpoint()
	h.EnableUpdateEndpoint()
	h.EnableListEndpoint()
	h.EnableUserEndpoint()
	h.EnableAccountEndpoint()
	return h
}

// Enable the create operation.
func (h *TransactionHandler) EnableCreateEndpoint() *TransactionHandler {
	h.Post("/", h.Create)
	return h
}

// struct to bind the post body to.
type transactionCreateRequest struct {
	Date    time.Time `json:"date,omitempty" `
	Amount  int       `json:"amount,omitempty" `
	User    int       `json:"user,omitempty" `
	Account int       `json:"account,omitempty" `
}

// This function creates a new Transaction model and stores it in the database.
func (h TransactionHandler) Create(w http.ResponseWriter, r *http.Request) {
	// Get the post data.
	d := transactionCreateRequest{} // todo - allow form-url-encdoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.Transaction.Create().
		SetDate(d.Date).
		SetAmount(d.Amount).
		SetUserID(d.User).
		SetAccountID(d.Account)

	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving Transaction")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"transaction:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Transaction.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("transaction", e.ID).Info("transaction rendered")
	render.OK(w, r, j)
}

// Enable the read operation.
func (h *TransactionHandler) EnableReadEndpoint() *TransactionHandler {
	h.Get("/{id:\\d+}", h.Read)
	return h
}

// This function fetches the Transaction model identified by a give url-parameter from
// database and returns it to the client.
func (h TransactionHandler) Read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Transaction.Query().Where(transaction.ID(id))

	e, err := qb.Only(r.Context())

	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).WithField("Transaction.id", id).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).WithField("Transaction.id", id).Error("duplicate entry for id")
			render.InternalServerError(w, r, nil)
			return
		default:
			h.logger.WithError(err).WithField("Transaction.id", id).Error("error fetching node from db")
			render.InternalServerError(w, r, nil)
			return
		}
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"transaction:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Transaction.id", id).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("transaction", e.ID).Info("transaction rendered")
	render.OK(w, r, d)
}

// Enable the update operation.
func (h *TransactionHandler) EnableUpdateEndpoint() *TransactionHandler {
	h.Get("/{id:\\d+}", h.Update)
	return h
}

// struct to bind the post body to.
type transactionUpdateRequest struct {
	Date    time.Time `json:"date,omitempty" `
	Amount  int       `json:"amount,omitempty" `
	User    int       `json:"user,omitempty" `
	Account int       `json:"account,omitempty" `
}

// This function updates a given Transaction model and saves the changes in the database.
func (h TransactionHandler) Update(w http.ResponseWriter, r *http.Request) {

	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	// Get the post data.
	d := transactionUpdateRequest{} // todo - allow form-url-encoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.Transaction.UpdateOneID(id).
		SetDate(d.Date).
		SetAmount(d.Amount).
		SetUserID(d.User).
		SetAccountID(d.Account)

	// Save in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving Transaction")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"transaction:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Transaction.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("transaction", e.ID).Info("transaction rendered")
	render.OK(w, r, j)
}

// Enable the list operation.
func (h *TransactionHandler) EnableListEndpoint() *TransactionHandler {
	h.Get("/", h.List)
	return h
}

// This function queries for Transaction models. Can be filtered by query parameters.
func (h TransactionHandler) List(w http.ResponseWriter, r *http.Request) {
	q := h.client.Transaction.Query()

	// Pagination
	var err error
	page := 1
	itemsPerPage := 30

	if d := r.URL.Query().Get("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("itemsPerPage", d).Info("error parsing query parameter 'itemsPerPage'")
			render.BadRequest(w, r, "itemsPerPage must be a positive integer greater zero")
			return
		}
	}

	if d := r.URL.Query().Get("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("page", d).Info("error parsing query parameter 'page'")
			render.BadRequest(w, r, "page must be a positive integer greater zero")
			return
		}
	}

	q = q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage)

	// Use the query parameters to filter the query. todo - nested filter?
	if f := r.URL.Query().Get("date"); f != "" {
		// todo
	}

	if f := r.URL.Query().Get("amount"); f != "" {
		i, err := strconv.Atoi(f)
		if err != nil {
			h.logger.WithError(err).WithField("amount", f).Debug("could not parse query parameter")
			render.BadRequest(w, r, "'amount' must be an integer")
			return
		}
		q = q.Where(transaction.Amount(i))
	}

	es, err := q.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"transaction:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("transaction rendered")
	render.OK(w, r, d)
}

// Enable the read operation on the user edge.
func (h *TransactionHandler) EnableUserEndpoint() *TransactionHandler {
	h.Get("/{id:\\d+}/user", h.User)
	return h
}

func (h TransactionHandler) User(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Transaction.Query().Where(transaction.ID(id)).QueryUser()

	e, err := qb.Only(r.Context())

	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).WithField("User.id", id).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).WithField("User.id", id).Error("duplicate entry for id")
			render.InternalServerError(w, r, nil)
			return
		default:
			h.logger.WithError(err).WithField("User.id", id).Error("error fetching node from db")
			render.InternalServerError(w, r, nil)
			return
		}
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"user:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("User.id", id).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("user", e.ID).Info("user rendered")
	render.OK(w, r, d)

}

// Enable the read operation on the account edge.
func (h *TransactionHandler) EnableAccountEndpoint() *TransactionHandler {
	h.Get("/{id:\\d+}/account", h.Account)
	return h
}

func (h TransactionHandler) Account(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.Transaction.Query().Where(transaction.ID(id)).QueryAccount()

	e, err := qb.Only(r.Context())

	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).WithField("Account.id", id).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).WithField("Account.id", id).Error("duplicate entry for id")
			render.InternalServerError(w, r, nil)
			return
		default:
			h.logger.WithError(err).WithField("Account.id", id).Error("error fetching node from db")
			render.InternalServerError(w, r, nil)
			return
		}
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"account:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("Account.id", id).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("account", e.ID).Info("account rendered")
	render.OK(w, r, d)

}

// The UserHandler.
type UserHandler struct {
	*chi.Mux

	client    *ent.Client
	validator *validator.Validate
	logger    *logrus.Logger
}

// Create a new UserHandler
func NewUserHandler(c *ent.Client, v *validator.Validate, log *logrus.Logger) *UserHandler {
	return &UserHandler{
		Mux:       chi.NewRouter(),
		client:    c,
		validator: v,
		logger:    log,
	}
}

// Enable all endpoints.
func (h *UserHandler) EnableAllEndpoints() *UserHandler {
	h.EnableCreateEndpoint()
	h.EnableReadEndpoint()
	h.EnableUpdateEndpoint()
	h.EnableListEndpoint()
	h.EnableSessionsEndpoint()
	h.EnableAccountsEndpoint()
	h.EnableTransactionsEndpoint()
	return h
}

// Enable the create operation.
func (h *UserHandler) EnableCreateEndpoint() *UserHandler {
	h.Post("/", h.Create)
	return h
}

// struct to bind the post body to.
type userCreateRequest struct {
	Email    string `json:"email,omitempty" `
	Password string `json:"password,omitempty" `
	Enabled  bool   `json:"enabled,omitempty" `
}

// This function creates a new User model and stores it in the database.
func (h UserHandler) Create(w http.ResponseWriter, r *http.Request) {
	// Get the post data.
	d := userCreateRequest{} // todo - allow form-url-encdoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.User.Create().
		SetEmail(d.Email).
		SetPassword(d.Password).
		SetEnabled(d.Enabled)

	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving User")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"user:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("User.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("user", e.ID).Info("user rendered")
	render.OK(w, r, j)
}

// Enable the read operation.
func (h *UserHandler) EnableReadEndpoint() *UserHandler {
	h.Get("/{id:\\d+}", h.Read)
	return h
}

// This function fetches the User model identified by a give url-parameter from
// database and returns it to the client.
func (h UserHandler) Read(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.User.Query().Where(user.ID(id))

	e, err := qb.Only(r.Context())

	if err != nil {
		switch err.(type) {
		case *ent.NotFoundError:
			h.logger.WithError(err).WithField("User.id", id).Debug("job not found")
			render.NotFound(w, r, err)
			return
		case *ent.NotSingularError:
			h.logger.WithError(err).WithField("User.id", id).Error("duplicate entry for id")
			render.InternalServerError(w, r, nil)
			return
		default:
			h.logger.WithError(err).WithField("User.id", id).Error("error fetching node from db")
			render.InternalServerError(w, r, nil)
			return
		}
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"user:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("User.id", id).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("user", e.ID).Info("user rendered")
	render.OK(w, r, d)
}

// Enable the update operation.
func (h *UserHandler) EnableUpdateEndpoint() *UserHandler {
	h.Get("/{id:\\d+}", h.Update)
	return h
}

// struct to bind the post body to.
type userUpdateRequest struct {
	Email    string `json:"email,omitempty" `
	Password string `json:"password,omitempty" `
	Enabled  bool   `json:"enabled,omitempty" `
}

// This function updates a given User model and saves the changes in the database.
func (h UserHandler) Update(w http.ResponseWriter, r *http.Request) {

	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	// Get the post data.
	d := userUpdateRequest{} // todo - allow form-url-encoded/xml/protobuf data.
	if err := json.NewDecoder(r.Body).Decode(&d); err != nil {
		h.logger.WithError(err).Error("error decoding json")
		render.BadRequest(w, r, "invalid json string")
		return
	}

	// Validate the data.
	if err := h.validator.Struct(d); err != nil {
		if err, ok := err.(*validator.InvalidValidationError); ok {
			h.logger.WithError(err).Error("error validating request data")
			render.InternalServerError(w, r, nil)
			return
		}

		h.logger.WithError(err).Info("validation failed")
		render.BadRequest(w, r, err)
		return
	}

	// Save the data.
	b := h.client.User.UpdateOneID(id).
		SetEmail(d.Email).
		SetPassword(d.Password).
		SetEnabled(d.Enabled)

	// Save in database.
	e, err := b.Save(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error saving User")
		render.InternalServerError(w, r, nil)
		return
	}

	// Serialize the data.
	j, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"user:read"}}, e)
	if err != nil {
		h.logger.WithError(err).WithField("User.id", e.ID).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("user", e.ID).Info("user rendered")
	render.OK(w, r, j)
}

// Enable the list operation.
func (h *UserHandler) EnableListEndpoint() *UserHandler {
	h.Get("/", h.List)
	return h
}

// This function queries for User models. Can be filtered by query parameters.
func (h UserHandler) List(w http.ResponseWriter, r *http.Request) {
	q := h.client.User.Query()

	// Pagination
	var err error
	page := 1
	itemsPerPage := 30

	if d := r.URL.Query().Get("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("itemsPerPage", d).Info("error parsing query parameter 'itemsPerPage'")
			render.BadRequest(w, r, "itemsPerPage must be a positive integer greater zero")
			return
		}
	}

	if d := r.URL.Query().Get("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			h.logger.WithField("page", d).Info("error parsing query parameter 'page'")
			render.BadRequest(w, r, "page must be a positive integer greater zero")
			return
		}
	}

	q = q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage)

	// Use the query parameters to filter the query. todo - nested filter?
	if f := r.URL.Query().Get("email"); f != "" {
		q = q.Where(user.Email(f))
	}

	if f := r.URL.Query().Get("password"); f != "" {
		q = q.Where(user.Password(f))
	}

	if f := r.URL.Query().Get("enabled"); f != "" {
		var b bool
		if f == "true" {
			b = true
		} else if f == "false" {
			b = false
		} else {
			h.logger.WithError(err).WithField("enabled", f).Debug("could not parse query parameter")
			render.BadRequest(w, r, "'enabled' must be 'true' or 'false'")
			return
		}
		q = q.Where(user.Enabled(b))
	}

	es, err := q.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"user:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("user rendered")
	render.OK(w, r, d)
}

// Enable the read operation on the sessions edge.
func (h *UserHandler) EnableSessionsEndpoint() *UserHandler {
	h.Get("/{id:\\d+}/sessions", h.Sessions)
	return h
}

func (h UserHandler) Sessions(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.User.Query().Where(user.ID(id)).QuerySessions()

	es, err := qb.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"session:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("session rendered")
	render.OK(w, r, d)

}

// Enable the read operation on the accounts edge.
func (h *UserHandler) EnableAccountsEndpoint() *UserHandler {
	h.Get("/{id:\\d+}/accounts", h.Accounts)
	return h
}

func (h UserHandler) Accounts(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.User.Query().Where(user.ID(id)).QueryAccounts()

	es, err := qb.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"account:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("account rendered")
	render.OK(w, r, d)

}

// Enable the read operation on the transactions edge.
func (h *UserHandler) EnableTransactionsEndpoint() *UserHandler {
	h.Get("/{id:\\d+}/transactions", h.Transactions)
	return h
}

func (h UserHandler) Transactions(w http.ResponseWriter, r *http.Request) {
	idp := chi.URLParam(r, "id")
	if idp == "" {
		h.logger.WithField("id", idp).Info("empty 'id' url param")
		render.BadRequest(w, r, "id cannot be ''")
		return
	}
	id, err := strconv.Atoi(idp)
	if err != nil {
		h.logger.WithField("id", idp).Info("error parsing url parameter 'id'")
		render.BadRequest(w, r, "id must be a positive integer greater zero")
		return
	}

	qb := h.client.User.Query().Where(user.ID(id)).QueryTransactions()

	es, err := qb.All(r.Context())
	if err != nil {
		h.logger.WithError(err).Error("error querying database") // todo - better error
		render.InternalServerError(w, r, nil)
		return
	}

	d, err := sheriff.Marshal(&sheriff.Options{Groups: []string{"transaction:list"}}, es)
	if err != nil {
		h.logger.WithError(err).Error("serialization error")
		render.InternalServerError(w, r, nil)
		return
	}

	h.logger.WithField("amount", len(es)).Info("transaction rendered")
	render.OK(w, r, d)

}
